@startuml
'https://plantuml.com/sequence-diagram

hide footbox

Participant ":Client" as client
Participant ":ServerController" as server
Participant ":ServerService" as service
participant ":Server" as game

-> client : leaveGame()
client -> server : POST/game/{serverID}/{robotID}
client <-- server : ACK
server -> service : leaveGame(serverID,robotID)
service -> game : removeRobot(robotID)

@enduml