@startuml
skinparam groupInheritance 2
skinparam linetype polyline

package httpclient{
   class Client{
      {Static} -HTTP_CLIENT : HttpClient
      -server : String
      -ServerID : String
      -connectedToServer : boolean
      -rootnumber : int

      +updateGame(String gameState) : void
      +getGameState() : String
      +hostGame(String title) : String
      +listGames() : String
      +joinGame(String serverToJoin) : String
      +leaveGame() : void
   }
   interface IStatusComm{
     +updateGame(String gameState) : void
     +getGameState() : String
     +hostGame(String title) : String
     +listGames() : String
     +joinGame(String serverToJoin) : String
     +leaveGame() : void
   }
   class Game{
      -id : String
      -title : String'
      -gameState : String
      -amountOfPlayers : int
      -maxAmountOfPlayers : int
      -playerSpotFilled : boolean
   }
   class GameListView{
       -stage : Stage
       -table : Tableview<Server>
       -data : ObservableList<Server>
        -app : AppController

        +addserver(String s) : void
        +viewTable() : void
   }
}

AppController -d- GameListView
IStatusComm <|.d. Client
Client - GameListView

@enduml