@startuml
'https://plantuml.com/sequence-diagram

hide footbox

Participant ":Player" as player
Participant ":Client" as client
Participant ":Game" as game

player -> client : getServerList()
client  -> game : getServerList()
client <-- game : Status code, message, List of servers
player <-- client : Server list
player -> client : Join Server(Server ID)
client -> game : Join Server(Server ID)
client <-- game : Status code, message
@enduml