@startuml
'https://plantuml.com/sequence-diagram

hide footbox

Participant ":Player" as player
Participant ":Client" as client
Participant ":Game" as game

player -> client : leaveGame()
client -> game : leaveGame(Server ID, Player ID)
client <-- game : Status code, message
@enduml