@startuml
'https://plantuml.com/sequence-diagram

hide footbox

Participant ":Client" as client
Participant ":ServerController" as server
Participant ":GameController" as gameController
participant ":Game" as game

-> client : createGame(String name)
client -> server : POST/game
server -> gameController : createGame(String name)
gameController -> game ** : init(String name)
gameController <-- game : String gameID
server <-- gameController : string gameID
client <-- server : String gameID
<-- client
-> client : updateGame()
alt startGame
    client->client : complete updateGame sequence
else player abandon game creation
    client->client : complete leaveGame sequence
end

@enduml