@startuml
'https://plantuml.com/sequence-diagram

hide footbox

Participant ":Client" as client
Participant ":ServerController" as server
Participant ":GameService" as gameService
participant ":Game" as game

-> client : createGame(String name)
client -> server : POST/game
server -> gameServer : createGame(String name)
gameServer -> game ** : init(String name)
gameServer <-- game : String gameID
server <-- gameServer : string gameID
client <-- server : String gameID
<-- client
-> client : updateGame()
alt startGame
    client->client : complete updateGame sequence
else player abandon game creation
    client->client : complete leaveGame sequence
end

@enduml