@startuml
'https://plantuml.com/sequence-diagram

hide footbox

Participant ":Client" as client
Participant ":ServerController" as server
Participant ":GameController" as gameController
participant ":Game" as game

-> client : listGame()
client -> server : GET/game
server -> gameController : listGame()
server <-- gameController : string listOfGames
client <-- server : string listOfGames
<-- client : string listOfGames
-> client : joinGame(string serverID)
client -> server : PUT/game
server -> gameController : joinGame(string serverID)
alt !serverFull && serverStillExist
    gameController -> game : addPlayer()
    gameController -> game : getRobot()
    gameController <-- game : string robotID
    server <-- gameController : string robotID
else player abandon game creation
    server <-- gameController : string errorMessage
end
client <-- server : string robotID
<-- client: String statusMessage

@enduml