@startuml
'https://plantuml.com/sequence-diagram

hide footbox

Participant ":Client" as client
Participant ":ServerController" as server
Participant ":GameService" as gameService
participant ":Game" as game

-> client : listGame()
client -> server : GET/game
server -> gameService : listGame()
server <-- gameService : string listOfGames
client <-- server : string listOfGames
<-- client : string listOfGames
-> client : joinGame(string serverID)
client -> server : PUT/game
server -> gameService : joinGame(string serverID)
alt !serverFull && serverStillExist
    gameService -> game : addPlayer()
    gameService -> game : getRobot()
    gameService <-- game : string robotID
    server <-- gameService : string robotID
else player abandon game creation
    server <-- gameService : string errorMessage
end
client <-- server : string robotID
<-- client: String statusMessage

@enduml