@startuml
'https://plantuml.com/sequence-diagram

hide footbox

Participant ":Client" as client
Participant ":ServerController" as server
Participant ":GameService" as gameService
participant ":Game" as game

-> client : leaveGame()
client -> server : POST/game/{serverID}/{robotID}
client <-- server : ACK
server -> gameService : leaveGame(serverID,robotID)
gameService -> game : removeRobot(robotID)

@enduml