@startuml
'https://plantuml.com/sequence-diagram

hide footbox

Participant ":Client" as client
Participant ":ServerController" as server
Participant ":GameController" as gameController
participant ":Game" as game

-> client : leaveGame()
client -> server : POST/game/{serverID}/{robotID}
client <-- server : ACK
server -> gameController : leaveGame(serverID,robotID)
gameController -> game : removeRobot(robotID)

@enduml