@startuml
'https://plantuml.com/sequence-diagram

hide footbox

Participant ":Client" as client
Participant ":ServerController" as server
Participant ":GameService" as gameService
participant ":Game" as game

-> client : getGameState()
client -> server : GET/gameState/{serverID}
server -> gameServioce : getGameState(serverID)
gameServioce -> game : getGameState()
gameServioce <-- game : string gameState
server <-- gameServioce : string gameState
client <-- server : string gameState

@enduml