@startuml
'https://plantuml.com/sequence-diagram

hide footbox

Participant ":Client" as client
Participant ":ServerController" as server
Participant ":GameController" as gameController
participant ":Game" as game

-> client : getGameState()
client -> server : GET/gameState/{serverID}
server -> gameController : getGameState(serverID)
gameController -> game : getGameState()
gameController <-- game : string gameState
server <-- gameController : string gameState
client <-- server : string gameState

@enduml