@startuml
'https://plantuml.com/sequence-diagram

hide footbox

Participant ":Client" as client
Participant ":ServerController" as server
Participant ":GameController" as gameController
participant ":Game" as game

-> client : setGameState()
client -> server : PUT/gameState/{serverID}
client <-- server : ACK
server -> gameController : setGameState(serverID, game)
gameController -> game : setGameState(game)

@enduml