@startuml
skinparam groupInheritance 2
skinparam linetype polyline

package designpatterns.observer{
   interface Observer{
      +update(Subject subject) : void
   }
   abstract class Subject{
      -observers : Set<Observer>

      #notifyChange() : void
      +attach(Observer observer) : void
      +detach(Observer observer) : void
   }
}

@enduml