@startuml
package fileaccess{
  class Adapter<E>{
     -CLASSNAME : String
     -INSTANCE : String

     +serialize : JsonElement
     +deserialize : E
  }
  class ReadWriteGame{
     {Static} -SAVED_BOARD_FOLDER : String
     {Static} -DEFAULT_BOARDS_FOLDER : String
     {Static} -JSON_EXT : String

     -getFilesInFolder(String folderName) : File[]
     +writeGameToDisk(String saveName, String json) : void
     +readGameFromDisk(String resourcePath) : String
     +getNamesOfSavedBoards() : List<String>
     +getNamesOfDefaultBoard() : List<String>

  }
  interface JsonDeserializer{
  }
  interface JsonSerializer {
  }
  class SerializeState{
     +serializeGame(Board board) : String
     +deserializeGame(String jsonString, boolean savedGame) : Board
  }

  note "This package is for saving or loading a game state" as note1
}

JsonDeserializer <|.. Adapter
JsonSerializer <|.. Adapter
Board *-l- SerializeState



@enduml