@startuml
'https://plantuml.com/sequence-diagram

hide footbox

Participant ":Player" as player
Participant ":Client" as client
Participant ":Server" as server

player -> client : leaveGame()
client -> server : leaveGame(Server ID, Player ID)
client <-- server : Status code, message
@enduml